### PR TITLE
chore(deps): Update dependencies

### PR DESCRIPTION
**Pull request by reneleonhardt**
Updated everything except JUnit.
If this pull request is accepted, a separate one will be submitted for JUnit 5 with lots of small code changes.

### CODE REVIEW

**Comment by pivovarit** [comment]
Looks good to me, thanks :)

**Comment by reneleonhardt** [comment]
You're welcome, thanks for merging :)
Didn't know there was a new maintainer, cool! Do you want to upgrade to JUnit Jupiter? JUnit 4 is 3 years old and EOL...

**Comment by pivovarit** [comment]
If you feel like it, then go and do it :) stretch goal: update https://github.com/vavr-io/vavr/tree/version/0.10.5 as well

**Comment by reneleonhardt** [comment]
> stretch goal: update https://github.com/vavr-io/vavr/tree/version/0.10.5 as well

I don't understand, 0.10.5 and 0.11.0 are extremely different from master, for example Maven instead of Gradle, let alone licenses, copyrights, docs, imports, code and tests.
What kind of branches are they? What is there to update?
Every release should be tagged from the default branch (master), or a child branch which just adds commits to the same base.

**Pull request merged**
