### PR TITLE
[draft] Removed Comparable from the list of interfaces implemented by Tuple

### LINKED ISSUE #2446: Tuple should not implement Comparable
In #605, we made Tuple* comparable in order to be used as element type in conjunction with SortedSet and SortedMap.

However, it might lead to a class cast exception at runtime, if the tuple components aren't comparable.

Screenshot 2019-12-07 at 17 34 08

Because we strive for more safety, we will remove the Comparable interface from the Tuple types.

### PR DESCRIPTION
**Pull request by pivovarit**
Closes #2446

### CODE REVIEW

**Comment by pivovarit** [comment]
It's a draft. Clicked the wrong button.

**Comment by pivovarit** [comment]
To be replaced with a proper `draft`

**Comment by danieldietrich** [comment]
Ok, thanks! This is an interesting topic, I hope I find some time tomorrow to think a bit about it...

**Comment by pivovarit** [comment]
That's definitely way harder than I thought :) the lack of `Comparable` bubbles up pretty aggressively. I will come back with a proposal (will play around with deriving internal comparators, mostly something along the lines:

```
Tuple2.comparator(comparator(), Comparators.naturalComparator())
```

**Comment by danieldietrich** [comment]
Yes, we had a reason for introducing it. But maybe there is a better/safer solution possible...

**Comment by danieldietrich** [comment]
I will assign you to the issue in order to mark it as 'occupied'. It helps me organizing the remaining issues for 1.0.0. No pressure, even if you decide not to do it..

**Pull request closed without merging**
