### PR TITLE
added method to help working with Validation when result is Seq of va…

### PR DESCRIPTION
**Pull request by CauchyPeano**
…lues

I found this method is useful while working with lists of values. 
For example when you need to validate list of values, and return either valid composite, or accumulated errors

### CODE REVIEW

**Comment by danieldietrich** [comment]
Hi Igor, thank you for your PR!

I think the new method does not scale well. It is a very specific use-case to cover `Seq<T>` only. Java users may prefer to use one of `java.util.*` collections instead, an `Iterable` or an array `T[]`.

Additionally, the API is not specific for `Validation` - all Vavr types than represent a Value, like `Option`, `Try`, etc. could have it.

The best way to achieve the result currently is:

```java
validation1.flatMap(seq1 -> validation2.map(seq1::appendAll));
```

Alternatively using Vavr's For-Comprehension (needs #2171 to be implemented):

```java
// currently the result is Iterable<Seq<String>>
// with #2171 the result will be Validation<E, Seq<T>>
For(validation1, validation2).yield(Seq::appendAll);
```

So I think we should close this PR.

**Comment by CauchyPeano** [comment]
Hi @danieldietrich,

Thanks for looking into my PR! I understand your reasoning, but still have a feeling that this direction could be useful. I've actually implemented parser for my project using Validation and find this case of using Seq<> within validation not so rare. 

I've also introduced this not just by my use-case, but looking at this method: 
`static <E, T> Validation<E, Seq<T>> sequence(Iterable<? extends Validation<E, T>> values)`

It introduces into the play validation of sequences, and this concept seems to be reasonable part of validation class. That's why I think this was a logical step to start introducing following method. 
(It was also present in [scalaz](https://github.com/scalaz/scalaz/blob/60719683de098efb7470af19e45b4002614fc2f1/core/src/main/scala/scalaz/Validation.scala#L302))

That's my opinion :)
Best,
Igor

**Comment by danieldietrich** [comment]
Scalaz has a general notion for that method. It isn't defined on a Scala companion object (which is the same as _static_ in Java) but as instance method of the class.

Also Scalaz does not restrict the _append_ method to Seq types but to Semigroups, i.e. all combinable types that obey specific rules.

Scalaz defines it once and it applies to all types. We would need to implement it as static method n-times on each type.

Additionally, it would lead to ambiguities, if we wanted to provide the same functionality for different inputs regarding the generic type argument. More specifically these methods could not exist side-by-side (from the perspective of a call-site):

```java
static <E, T> Validation<E, Seq<T>> append(Validation<E, Seq<T>> first, Validation<E, Seq<T>> second) { ... }

static <E, T> Validation<E, Set<T>> append(Validation<E, Set<T>> first, Validation<E, Set<T>> second) { ... }
```

Validation.sequence is of a different flavor. The return type is baked into the method name. In contrast to the example above different implementations could therefore co-exist. The only drawback is, that we also have to implement it n-times.

```java
static <E, T> Validation<E, Seq<T>> sequence(Iterable<? extends Validation<E, T>> values) { ... }

static <E, T> Validation<E, Set<T>> distinct(Iterable<? extends Validation<E, T>> values) { ... }
```

The static _sequence_ method exists because we do not have any alternatives. For _append_ it is a different case, we have a relatively concise alternative (see my [previous comment](https://github.com/vavr-io/vavr/pull/2211#issuecomment-365192767)).

```java
static <E, T> Validation<E, Seq<T>> sequence(Iterable<? extends Validation<E, T>> values) {
    Objects.requireNonNull(values, "values is null");
    List<E> errors = List.empty();
    List<T> list = List.empty();
    for (Validation<E, T> value : values) {
        if (value.isInvalid()) {
            errors = errors.prependAll(value.getErrors().reverse());
        } else if (errors.isEmpty()) {
            list = list.prepend(value.get());
        }
    }
    return errors.isEmpty() ? valid(list.reverse()) : invalidAll(errors.reverse());
}
```

---

These static methods generally are a pain in the ass from the perspective of a maintainer. We can't statically check, if all classes implement them (the right way). It is kind of code duplication.

**Comment by CauchyPeano** [comment]
Hi @danieldietrich, 
I agree, here we are bumping into java's limitations. I've also noted that it would make sense to have it not as static method, but it's not feasible
Thanks for explanation!

**Comment by danieldietrich** [comment]
Thanks!

**Pull request closed without merging**
