### PR TITLE
Annotate generated classes with `@Generated`

### LINKED ISSUE #2081: Annotate generated classes with @Generated
Generated classes like [CheckedFunction0](https://github.com/vavr-io/vavr/blob/ec2d9b4337004792e786b42e0ac3eddc6ddf4bc8/vavr/src-gen/main/java/io/vavr/CheckedFunction0.java#L41) could be annotated with `javax.annotation.Generated` to differentiate them from hand written code.

Furthermore the generator class as well as the actual generator method could be referenced via the comment attribute to ease finding the appropriate generator method.

### PR DESCRIPTION
**Pull request by valery1707**
Fix #2081

### CODE REVIEW

**Comment by danieldietrich** [comment]
Awesome, thank you 😊

**Comment by talios** [comment]
Note that `@Generated` is no longer available in JDK 9 ( its part of the EE jars/modules, which aren't enabled by default, and are deprecated) - but are available via a dependency.

**Comment by danieldietrich** [comment]
@talios thanks for the hint! I will create an issue.

**Note:** Because of #1716 we will have a new code generator. The 'inline' generated code will not be annotated with `@Generated` anymore. See also [this tweet](https://twitter.com/danieldietrich/status/926846450016931840).

**Comment by talios** [comment]
@danieldietrich See https://github.com/immutables/immutables/issues/703#issuecomment-342029844 for a related discussion.  Seems Java 9 added `javax.annotation.processing.Generated` :)

**Pull request merged**
