### PR TITLE
Upgrade to JUnit 5

### PR DESCRIPTION
**Pull request by reneleonhardt**
### Internal
* Upgrade to JUnit 5

### CODE REVIEW

**Comment by reneleonhardt** [comment]
### Notes
* Please squash the commits upon merging, I tried to separate a few fixes
* I added Java 21 to the matrix, I thought I already did that in my update PR... 🤷

**Comment by pivovarit** [comment]
Looks good, thanks!

I have one question. I tried running tests on `master` and your branch, and there are more tests running on yours. Do you have any idea why is that?

master:
image

yours:
Screenshot 2024-08-23 at 10 58 03

That's obviously

**Comment by pivovarit** [comment]
@reneleonhardt I'd love to merge this one - do you have any clue why this happens?

https://github.com/vavr-io/vavr/pull/2804#issuecomment-2306664375

**Comment by reneleonhardt** [comment]
JUnit 4 and 5 are totally different, look at the XML report, the test names are different as is the structure (i.e. nested classes).
It would be extremely hard to match 33,000 tests 1:1, I tried 😅
My recommendation would be to enable coverage, then you would have just 2 numbers to compare.
Extracting 2 file lists from that would be much easier to diff.

**Comment by pivovarit** [comment]
image

Amazing work, thanks :)

**Pull request merged**
