### PR TITLE
changed signature of Future.andThen (#2183)

### PR DESCRIPTION
**Pull request by CauchyPeano**
After careful reading of related thread discussion and reasoning, I've understood that only this small change is needed to be done.

Please correct me if i'm wrong.

### CODE REVIEW

**Comment by danieldietrich** [comment]
Could you please point to the related discussion? I'm not aware of the topic. Thx!

**Comment by CauchyPeano** [comment]
Yep, it's this one: https://github.com/vavr-io/vavr/issues/2183

**Comment by danieldietrich** [comment]
Hi Igor,

I tried to recapitulate what my intention was creating issue #2183.

In Scala, we have different conditions than in Java. Scala does not distinguish between suppliers, consumers, runnables and functions - there are just... functions. This is because there is no distinguished return type 'void'.

This is the reason why Scala's Future.onComplete(), foreach() and andThen() take functions. The returned value is just ignored - it might be a value, or just Unit (see also [the difference between Nothing and Unit in Scala](https://stackoverflow.com/a/13539858/1110815)).

Future's methods onComplete(), forEach() and andThen() are intended to perform side-effects. In Java, the only way to express this is using Consumer as argument. **If we use Function, we effectively have to return something. This is the most important difference to Scala.**

I'm afraid, therefore we have to keep the original forEach(Consumer).

I will close this PR and also my issue. This is not the right way to do it in Java.

Sorry, I really appreciate your effort and your contribution! I hope you understand.

**Comment by CauchyPeano** [comment]
Hi @danieldietrich,

no problem. Reasoning is completely clear for me. Luckily change was not so big :) 

If there any tickets which are bothering you and you need help with, I will be glad to work on them.

Cheers, 
Igor

**Comment by danieldietrich** [comment]
@CauchyPeano thanks!

You could take a look at #1629. I will assist you on any questions!
It involves the code generator.

**Pull request closed without merging**
