### PR TITLE
Add Either For comprehension 

### PR DESCRIPTION
**Pull request by alexandrustana**
A possible implementation for  #2383

### CODE REVIEW

**Comment by danieldietrich** [comment]
Hi @alexandrustana, thank you! That Looks good to me :)
The build currently fails because you manually changed the generated code in `src-gen/`.
We need to change the `generator/Generator.scala` to
1. generate API.java
2. generate APITest.java
Do you think you can do that? It is a bit Scala but you can copy/past existing stuff and substitute Either.
Thx!

**Comment by alexandrustana** [comment]
Hello @danieldietrich 
I'll try this evening or tomorrow morning to modify the `Generator.scala`.

Thanks for the help with the failing build.

**Comment by danieldietrich** [comment]
Cool, thank you! Please start the following tasks locally:

`mvn clean test` to test your changes.

`mvn javadoc:javadoc` to lint the documentation.

**Comment by danieldietrich** [comment]
Thank you, that looks awesome! 🎉

**Pull request merged**
