### PR TITLE
Change license to the MIT license

### LINKED ISSUE #2680: Change license to MIT
I like openness, Vavr is non-commercial. Changing the license to MIT makes it easier for commercial software to adopt Vavr.

### PR DESCRIPTION
**Pull request by micrommer**
To resolve #2680 issue.

### CODE REVIEW

**Review by danieldietrich — CHANGES_REQUESTED** [review]
Hi @micrommer and thank you for your contribution!
The changeset looks really great - you found all spots I can imagine.
I recognized that the two files `LICENSE` and `COPYRIGHT` are now identical. Could you please remove the `COPYRIGHT` file? Do you think it is referenced somewhere else (verbally)?
Thank you!
Daniel

**Comment by micrommer** [comment]
Hi dear @danieldietrich,
It seems the only `COPYRIGHT` usage was in the Gradle script, you can find the file creation on 2f2304daf83924ef8c7fc5f7779153af80da149c, Maybe @tobi5775 could confirm the usage.

Best reagards.

**Comment by danieldietrich** [comment]
@micrommer yes, I can confirm that. Please remove the `COPYRIGHT` file and change the occurrence in the Gradle script to the `LICENSE` file.
Thank you

**Comment by micrommer** [comment]
Hi @danieldietrich,
It has already been done in #2738.
Thank you

**Review by danieldietrich — APPROVED** [review]
Well done, I am very happy with it! Thx

**Pull request merged**
