### PR TITLE
Initial introduction of partially implemented Range class

### PR DESCRIPTION
**Pull request by sleepytomcat**
This draft PR is to address https://github.com/vavr-io/vavr/issues/2666

### CODE REVIEW

**Comment by sleepytomcat** [comment]
@danieldietrich please let know if this looks like an overall direction you envisioned.

**Comment by sleepytomcat** [comment]
Note: this is still a draft, some parts are missing (i.e. documentation, specialization for Double, etc.)

**Comment by danieldietrich** [comment]
Hi @sleepytomcat, this is a duplicate to my effort in #2490. I already put much effort into it and would like to finish it.
I will close this as duplicate and prepare a PR.

Sorry for having to close your PR. I really appreciate your effort.

**Comment by sleepytomcat** [comment]
Sure, no problem!

@danieldietrich I'm looking forward to v1.0.0 release — any suggestions how I could contribute? Thank you.

**Pull request closed without merging**
